# Generated by Django 3.0.8 on 2020-07-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_auto_20200727_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='eshop/images'),
        ),
    ]
